
var leads=[
 {id:'biblioteca',name:'Biblioteca',icon:'📚',x:21,y:39,room:'library',clue:'Tarjeta de espacio tranquilo',object:'🔖',puzzle:'Alex quiere hablar sin que el curso escuche. ¿Qué lugar da más privacidad y permite pedir orientación?',answers:['La biblioteca, para conversar con una persona adulta de confianza en un espacio tranquilo.','El patio, en medio del recreo.','Publicar una nota en el mural para que cualquiera responda.'],correct:0,hint:'Busca un lugar tranquilo y una persona adulta segura; no hace falta hacer pública la situación.',npc:'Bibliotecaria',emoji:'👩🏻‍🏫',talk:'La biblioteca puede ser un sitio tranquilo. La orientadora está disponible en horario escolar.'},
 {id:'pasillo',name:'Pasillo',icon:'🧭',x:50,y:39,room:'hall',clue:'Horario de orientación',object:'🗓️',puzzle:'El cartel tiene tres símbolos: un megáfono en el patio, una puerta abierta en el auditorio y una estrella junto a orientación. ¿Cuál pista ayuda a hablar en privado?',answers:['El megáfono: así toda la escuela puede ayudar.','La estrella junto a orientación: indica un espacio de apoyo.','El auditorio: es grande y visible.'],correct:1,hint:'La pista útil conecta el espacio privado con una persona adulta que pueda ayudar.',npc:'Lía',emoji:'👩🏻',talk:'Leí el horario: podemos buscar a orientación después de clases. No compartamos esto con todo el curso.'},
 {id:'aula',name:'Aula',icon:'🧑‍🏫',x:79,y:39,room:'classroom',clue:'Nota de acompañamiento',object:'📝',puzzle:'Sam quiere ayudar, pero no sabe todos los detalles. ¿Qué acción cuida mejor a Alex?',answers:['Investigar por su cuenta y confrontar a la familia.','Prometer que jamás se lo dirá a una persona adulta.','Preguntar qué necesita y ofrecer acompañarle a una persona adulta segura.'],correct:2,hint:'Sam puede escuchar y acompañar; una persona adulta segura se encarga de activar la ruta de apoyo.',npc:'Docente',emoji:'👩🏾‍🏫',talk:'Puedo acompañar a Alex a orientación. Si hay riesgo, debemos pedir ayuda siguiendo la ruta escolar.'}
];
var finalPuzzle={question:'Combinen las tres evidencias y armen una ruta segura. ¿Qué secuencia tiene sentido?',answers:['Escuchar → preguntar qué necesita → acompañar a una persona adulta segura → seguir la ruta escolar.','Investigar → contar al curso → confrontar → esperar.','Pedir detalles → decidir por Alex → publicar → actuar a solas.'],correct:0,hint:'La ruta empieza con escucha respetuosa y termina con apoyo adulto capacitado.'};
var mode='hub',activeLead=-1,px=50,py=84,near=null,found=[],talked=[],wrong=[],keys={},dialogOpen=false,seconds=300,overtime=false,lastSecond=0,lastMove=0,touchDir='';
function byId(id){return document.getElementById(id)}function has(a,v){return a.indexOf(v)!==-1}
function personHtml(name,type,x,y,id){return '<div class="sprite '+type+'" '+(id?'id="'+id+'"':'')+' style="left:'+x+'%;top:'+y+'%"><span class="hair"></span><span class="head"></span><span class="neck"></span><span class="torso"></span><span class="arm left"></span><span class="arm right"></span><span class="leg left"></span><span class="leg right"></span><span class="shoe left"></span><span class="shoe right"></span><span class="label">'+name+'</span></div>'}
function startGame(){mode='hub';activeLead=-1;px=50;py=84;found=[];talked=[];wrong=[];seconds=300;overtime=false;lastSecond=0;lastMove=0;byId('home').style.display='none';byId('finish').style.display='none';byId('game').className='game active';showHub();nextFrame()}
function nextFrame(){if(window.requestAnimationFrame)window.requestAnimationFrame(loop);else window.setTimeout(function(){loop(new Date().getTime())},33)}
function showHub(){mode='hub';activeLead=-1;px=50;py=83;var stage=byId('stage');stage.className='stage hub';byId('loc').textContent='Mapa abierto · elige una pista';byId('objective').textContent=found.length<3?'Visita Biblioteca, Pasillo y Aula en cualquier orden. Reúne sus tres evidencias.':'Las tres evidencias están reunidas. Ve al tablero central y resuelve el código.';var html='<div class="map-label">Explora los lugares en cualquier orden</div>';for(var i=0;i<leads.length;i++){var l=leads[i],done=has(found,l.id);html+='<button class="node'+(done?' done':'')+'" data-lead="'+i+'" style="left:'+l.x+'%;top:'+l.y+'%"><span class="icon">'+(done?'✓':l.icon)+'</span><span class="label">'+l.name+'</span><span class="status">'+(done?'Evidencia reunida':'Investigar →')+'</span></button>'}if(found.length===3)html+='<button class="node" data-final="1" style="left:50%;top:72%;border-color:#ffd36e"><span class="icon">🔐</span><span class="label">Tablero del caso</span><span class="status">Combinar evidencias</span></button>';html+=personHtml('Sam','sam',px,py,'avatar');byId('world').innerHTML=html;var nodes=byId('world').querySelectorAll('[data-lead]');for(var j=0;j<nodes.length;j++)nodes[j].onclick=function(){enterLead(Number(this.getAttribute('data-lead')))};var finalNode=byId('world').querySelector('[data-final]');if(finalNode)finalNode.onclick=openFinal;drawHud();findTarget()}
function enterLead(i){if(has(found,leads[i].id)&&has(talked,leads[i].id)){toast('Esa evidencia ya está reunida. Elige otro lugar.');return}mode='room';activeLead=i;px=17;py=77;var l=leads[i],stage=byId('stage'),type=i===0?'librarian':i===1?'lia':'teacher';stage.className='stage '+l.room;byId('loc').textContent=l.name+' · búsqueda de evidencia';byId('objective').textContent=has(found,l.id)?'Evidencia reunida. Conversa con '+l.npc+' o vuelve al mapa.':'Explora el lugar. Encuentra '+l.clue+' y resuelve el acertijo con tu equipo.';byId('world').innerHTML='<div class="sun"></div><div class="window win1"></div><div class="window win2"></div><div class="window win3"></div><div class="floor"></div><div class="rug"></div><div class="plant">🪴</div><div class="desk"></div><button class="exit" id="exit">← Volver al mapa</button>'+(has(found,l.id)?'':'<div class="room-clue" style="left:53%;top:63%"><span>'+l.object+'</span><span>'+l.clue+'</span></div>')+personHtml(l.npc,type,79,65,'npc-sprite')+personHtml('Sam','sam',px,py,'avatar');byId('exit').onclick=showHub;var exitReady=has(found,l.id)&&has(talked,l.id);if(exitReady)byId('exit').className='exit ready';drawHud();findTarget()}
function drawHud(){byId('pips').innerHTML='';byId('clues').innerHTML='';for(var i=0;i<leads.length;i++){var yes=has(found,leads[i].id),pip=document.createElement('i');pip.className='pip'+(yes?' done':'');byId('pips').appendChild(pip);var row=document.createElement('div');row.className='clue'+(yes?' done':'');row.innerHTML='<b>'+(yes?'✓':'○')+'</b><span>'+(yes?leads[i].clue:'Evidencia por descubrir')+'</span>';byId('clues').appendChild(row)}byId('meter').style.width=(found.length/3*100)+'%';updateClock()}
function distance(x,y){var dx=(x-px)*10,dy=(y-py)*5.6;return Math.sqrt(dx*dx+dy*dy)}
function findTarget(){near=null;if(mode==='hub'){for(var i=0;i<leads.length;i++)if(!has(found,leads[i].id)&&distance(leads[i].x,39)<100){near={kind:'lead',id:i,label:'Investigar '+leads[i].name};break}if(!near&&found.length===3&&distance(50,72)<115)near={kind:'final',label:'Abrir el tablero del caso'}}else if(mode==='room'){var l=leads[activeLead];if(!has(found,l.id)&&distance(53,63)<105)near={kind:'clue',label:'Examinar '+l.clue};else if(has(found,l.id)&&!has(talked,l.id)&&distance(79,65)<110)near={kind:'person',label:'Hablar con '+l.npc}}var p=byId('prompt');if(near){p.textContent='E · '+near.label;p.style.display='block'}else p.style.display='none'}
function move(dx,dy){if(mode==='hub'){px=Math.max(5,Math.min(95,px+dx*1.4));py=Math.max(20,Math.min(92,py+dy*1.8))}else{px=Math.max(8,Math.min(92,px+dx*1.4));py=Math.max(45,Math.min(91,py+dy*1.8))}var a=byId('avatar');if(a){a.style.left=px+'%';a.style.top=py+'%';a.className='sprite sam moving';window.setTimeout(function(){if(a)a.className='sprite sam'},220)}findTarget()}
function interact(){if(dialogOpen)return;if(!near){toast('Acércate a una pista, persona o tablero.');return}if(near.kind==='lead')enterLead(near.id);else if(near.kind==='clue')openPuzzle(activeLead);else if(near.kind==='person')openTalk(activeLead);else if(near.kind==='final')openFinal()}
function openPuzzle(i){var p=leads[i];showQuestion('Acertijo de evidencia · '+p.name,p.puzzle,p.answers,p.correct,p.hint,function(){if(!has(found,p.id))found.push(p.id);drawHud();byId('objective').textContent='Evidencia reunida. Ahora conversa con '+p.npc+' antes de volver al mapa.';enterLead(i);toast('Evidencia añadida al tablero')})}
function showQuestion(title,question,answers,correct,hint,onCorrect){dialogOpen=true;wrong=[];byId('speaker').textContent=title;byId('dialog-text').textContent=question+(overtime?' Pista extra: '+hint:'');renderAnswers(answers,correct,hint,onCorrect);byId('dialog-wrap').className='dialog-wrap show'}
function renderAnswers(answers,correct,hint,onCorrect){var html='';for(var i=0;i<answers.length;i++)if(!has(wrong,i))html+='<button class="choice" data-answer="'+i+'"><strong>'+(i+1)+'.</strong>'+answers[i]+'</button>';byId('choices').innerHTML=html;var buttons=byId('choices').getElementsByTagName('button');for(var j=0;j<buttons.length;j++)buttons[j].onclick=function(){var n=Number(this.getAttribute('data-answer'));if(n===correct){byId('dialog-text').textContent='¡Buena deducción! '+hint;byId('choices').innerHTML='<button class="btn" id="continue">Guardar evidencia →</button>';byId('continue').onclick=function(){byId('dialog-wrap').className='dialog-wrap';dialogOpen=false;onCorrect()};return}wrong.push(n);byId('dialog-text').textContent='Esa opción no encaja todavía. Pista: '+hint+' Conversen y prueben otra respuesta.';renderAnswers(answers,correct,hint,onCorrect)}}
function openTalk(i){var l=leads[i];dialogOpen=true;byId('speaker').textContent=l.npc;byId('dialog-text').textContent=l.talk;byId('choices').innerHTML='<button class="choice" id="talk1">1. «Gracias por ayudar. ¿Puedes acompañarme a orientación?»</button><button class="choice" id="talk2">2. «Voy a contárselo a otras personas para que averigüen.»</button>';byId('talk1').onclick=function(){finishTalk(i,'Buena decisión: pedir compañía y cuidar la privacidad ayuda a conectar con apoyo seguro.')};byId('talk2').onclick=function(){finishTalk(i,'Compartirlo puede exponer a Alex. Mejor pregunta qué necesita y busca apoyo adulto en privado.')};byId('dialog-wrap').className='dialog-wrap show'}
function finishTalk(i,feedback){talked.push(leads[i].id);byId('dialog-text').textContent=feedback;byId('choices').innerHTML='<button class="btn" id="backmap">Volver al mapa →</button>';byId('backmap').onclick=function(){dialogOpen=false;byId('dialog-wrap').className='dialog-wrap';showHub()}}
function openFinal(){if(found.length<3){toast('Primero reúne las tres evidencias.');return}var p=finalPuzzle;showQuestion('Código final · combinar evidencias',p.question,p.answers,p.correct,p.hint,function(){byId('game').className='game';byId('finish').style.display='block'})}
function updateClock(){var m=Math.floor(seconds/60),s=seconds%60;byId('clock').textContent=overtime?'TIEMPO EXTRA':(m<10?'0':'')+m+':'+(s<10?'0':'')+s;if(seconds<60&&!overtime)byId('clock').style.color='#ffd36e'}
function loop(now){if(byId('game').className.indexOf('active')<0)return;if(!dialogOpen&&byId('care').className.indexOf('show')<0){if(!lastSecond)lastSecond=now;if(now-lastSecond>=1000){lastSecond=now;if(seconds>0)seconds--;if(seconds===0&&!overtime){overtime=true;toast('Se acabó el reloj, no la investigación. Ahora recibes pistas.')}updateClock()}if(touchDir&&now-lastMove>110){if(touchDir==='left')move(-1,0);if(touchDir==='right')move(1,0);if(touchDir==='up')move(0,-1);if(touchDir==='down')move(0,1);lastMove=now}}nextFrame()}
function onKeyDown(e){var k=e.key,low=k.toLowerCase(),dir=null;if(k.indexOf('Arrow')===0||k===' ')e.preventDefault();keys[k]=true;keys[low]=true;if(k==='ArrowLeft'||low==='a')dir=[-1,0];if(k==='ArrowRight'||low==='d')dir=[1,0];if(k==='ArrowUp'||low==='w')dir=[0,-1];if(k==='ArrowDown'||low==='s')dir=[0,1];if(dir&&!dialogOpen&&byId('care').className.indexOf('show')<0&&new Date().getTime()-lastMove>85){move(dir[0],dir[1]);lastMove=new Date().getTime()}if(k==='e'||k==='E'||k===' ')interact();if(dialogOpen&&'123'.indexOf(k)!==-1){var bs=byId('choices').getElementsByTagName('button');for(var i=0;i<bs.length;i++)if(bs[i].getAttribute('data-answer')===String(Number(k)-1)){bs[i].click();break}}if(k==='Escape'){closeCare();byId('dialog-wrap').className='dialog-wrap';dialogOpen=false}}
function onKeyUp(e){keys[e.key]=false;keys[e.key.toLowerCase()]=false}
function toast(s){var t=byId('toast');t.textContent=s;t.className='toast show';window.setTimeout(function(){t.className='toast'},1500)}
function openCare(){byId('care').className='care-wrap show'}function closeCare(){byId('care').className='care-wrap'}function toggleProject(){document.body.classList.toggle('project');if(document.documentElement.requestFullscreen){var p=document.documentElement.requestFullscreen();if(p&&p.catch)p.catch(function(){})}}
function restart(){byId('finish').style.display='none';byId('home').style.display='grid';byId('game').className='game'}
byId('start').onclick=startGame;document.addEventListener('keydown',onKeyDown);document.addEventListener('keyup',onKeyUp);var pads=document.querySelectorAll('[data-dir]');for(var pi=0;pi<pads.length;pi++){pads[pi].onpointerdown=function(e){e.preventDefault();touchDir=this.getAttribute('data-dir');if(touchDir==='left')move(-1,0);if(touchDir==='right')move(1,0);if(touchDir==='up')move(0,-1);if(touchDir==='down')move(0,1)};pads[pi].onpointerup=pads[pi].onpointercancel=function(){touchDir=''}}

